version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/fitness
      - MQTT_BROKER_URL=http://147.232.205.176/mqttexplorer/
      - MQTT_TOPIC=fitness/training
      - MQTT_USERNAME=maker
      - MQTT_PASSWORD=mother.mqtt.password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
